DATA_FILE_PATH = 'data.csv'
TITLE=0 # Index of col TITLE
FIRST_NAME=1 # Index of col FIRST_NAME
LAST_NAME=2 # Index of col LAST_NAME
EMAIL=3 # Index of col EMAIL
NUM_OF_COL=4 # Num of col in CSV file
TITLE_LENGTH_MIN=5 # Min length of string random
TITLE_LENGTH_MAX=10 # Max length of string random
FIRST_NAME_MIN=5 # Min length of string random
FIRST_NAME_MAX=10 # Max length of string random
LAST_NAME_MIN=5 # Min length of string random
LAST_NAME_MAX=10 # Max length of string random
EMAIL_ADDRESS_MIN=6 # Min length of string random
EMAIL_ADDRESS_MAX=10 # Max length of string random
EMAIL_POST_FIX='@example.com' # Postfix of email
HEADER = ['TITLE', 'FIRST_NAME', 'LAST_NAME', 'EMAIL'] # Header of csv file

FILE_ERROR_PATH = 'error.csv' # Error file path
TEMPLATE_JSON_PATH='template.json' # File template for email
TEMPLATE_REPLACE_PATH='templateReplace.json' # Template add or replace properties in JSON
ADD='add'
REPLACE='replace'
SPECIFIC_REPLACE='specific_replace'
PROPERTY='property'
PREFIX='prefix'
COL='col'
POSTFIX='postfix'
VALUE='value'

CSV_PATH='data.csv'
JSON_FOLDER_PATH='json_folder' # JSON folder for the result